---
qubes_software:
  debian-11-base:
    - bat
    - delta
    - direnv
    - etcd
    - fd
    - ffsend
    - fm
    - gping
    - jq
    - task
    - yq
  dev-tmpl: '{{ software }}'
  fedora-36-base:
    - bat
    - delta
    - direnv
    - etcd
    - fd
    - ffsend
    - fm
    - gping
    - jq
    - task
    - yq
  kubernetes-tmpl:
    - kdash
    - kn
    - kubenav
    - linkerd2
  media-tmpl:
    - webtorrent
  personal-tmpl:
    - bitwarden
    - raindrop
  services-tmpl:
    - g-assist
