---
# yamllint disable rule:line-length
# @var nodejs_npm_global_packages: [] # A list of NPM packages to install globally.
nodejs_npm_global_packages:
  # @npm @cli [@angular/cli](https://npmjs.com/package/@angular/cli) | [GitHub](https://github.com/angular/angular-cli) | [Homepage](https://angular.io/) | [Documentation](https://angular.io/docs) - Official CLI for [Angular](https://angular.io/) capable of generating new projects, generating boilerplate files, and testing apps with LiveReload
  - name: '@angular/cli'
    bin: ng

  # @npm @cli [@cloudflare/wrangler](https://npmjs.com/package/@cloudflare/wrangler) | [GitHub](https://github.com/cloudflare/wrangler) | [Homepage](https://workers.cloudflare.com/) | [Documentation](https://developers.cloudflare.com/workers/wrangler/configuration/) - A CLI tool designed for folks who are interested in using Cloudflare Workers
  - name: '@cloudflare/wrangler'
    bin: wrangler

  # @npm @cli [@feathersjs/cli](https://npmjs.com/package/@feathers/cli) | [GitHub](https://github.com/feathersjs/feathers) | [Homepage](https://feathersjs.com/) | [Documentation](https://docs.feathersjs.com/) - Feathers is a lightweight web-framework for creating real-time applications and REST APIs using JavaScript or TypeScript.
  - name: '@feathersjs/cli'
    bin: feathers

  # @npm @cli [@ionic/cli](https://npmjs.com/package/@ionic/cli) | [GitHub](https://github.com/ionic-team/ionic-cli) | [Homepage](https://ionicframework.com/) | [Documentation](https://ionicframework.com/docs/intro/cli) - A command line interface (CLI) is go-to tool for developing Ionic apps
  - name: '@ionic/cli'
    bin: ionic

  # @npm @cli [@nestjs/cli](https://npmjs.com/package/@nestjs/cli) | [GitHub](https://github.com/nestjs/nest-cli) | [Homepage](https://nestjs.com/) | [Documentation](https://docs.nestjs.com/) - A command-line interface tool that helps you to initialize, develop, and maintain your Nest applications
  - name: '@nestjs/cli'
    bin: nest

  # @npm @cli [@sentry/cli](https://npmjs.com/package/@sentry/cli) | [GitHub](https://github.com/getsentry/sentry-cli) | [Homepage](https://sentry.io/welcome/) | [Documentation](https://docs.sentry.io/product/cli/) - A Sentry command line client for some generic tasks
  - name: '@sentry/cli'
    bin: sentry-cli

  # @npm @cli [@vercel/ncc](https://npmjs.com/package/@vercel/ncc) | [GitHub](https://github.com/vercel/ncc) | [Homepage](https://github.com/vercel/ncc#readme) - CLI for compiling a Node.js module into a single file, together with all its dependencies, gcc-style
  - name: '@vercel/ncc'
    bin: ncc

  # @npm @cli [auto-install](https://npmjs.com/package/auto-install) | [GitHub](https://github.com/siddharthkp/auto-install) | [Homepage](https://github.com/siddharthkp/auto-install#readme) - Auto installs dependencies as you code
  - name: auto-install
    bin: auto-install

  # @npm @cli [bitly-cli-client](https://npmjs.com/package/bitly-cli-client) | [GitHub](https://github.com/xxczaki/bitly-cli-client) | [Homepage](https://github.com/xxczaki/bitly-cli-client#readme) - Shorten links with Bitly in the terminal
  - name: bitly-cli-client
    bin: bitly

  # @npm @cli [browser-sync](https://browsersync.io/) | [GitHub](https://github.com/BrowserSync/browser-sync) | [Homepage](http://browsersync.io/) | [Documentation](https://browsersync.io/docs) - Time-saving synchronized browser testing - test desktop and mobile versions of a website at the same time
  - name: browser-sync
    bin: browser-sync

  # @npm @cli [caniuse-cmd](https://npmjs.com/package/caniuse-cmd) | [GitHub](https://github.com/sgentle/caniuse-cmd) | [Homepage](https://caniuse.com/) | [Documentation](https://github.com/sgentle/caniuse-cmd#readme) - Caniuse command line tool
  - name: caniuse-cmd
    bin: caniuse

  # @npm @cli [carbon-now-cli](https://npmjs.com/package/carbon-now-cli) | [GitHub](https://github.com/mixn/carbon-now-cli) | [Homepage](https://carbon.now.sh/) - Tool that generates beautiful images of source code through an intuitive UI, while customizing aspects like fonts, themes, window controls and much mor
  - name: carbon-now-cli
    bin: carbon-now

  # @npm @cli [commitizen](https://npmjs.com/package/commitizen) | [GitHub](https://github.com/commitizen/cz-cli) | [Homepage](https://commitizen.github.io/cz-cli/) | [Documentation](https://github.com/commitizen/cz-cli/blob/master/README.md) - The commitizen command line utility
  - name: commitizen
    bin: cz

  # @npm @cli [cordova](https://npmjs.com/package/cordova) | [GitHub](https://github.com/apache/cordova-android) | [Homepage](https://cordova.apache.org/) | [Documentation](https://cordova.apache.org/docs/en/latest/) - The command line tool to build, deploy and manage Cordova-based applications
  - name: cordova
    bin: cordova

  # @npm @cli [deviceframe](https://npmjs.com/package/deviceframe) | [GitHub](https://github.com/c0bra/deviceframe) | [Homepage](https://github.com/c0bra/deviceframe#readme) - Put device frames around mobile/web/progressive app screenshots
  - name: deviceframe
    bin: dframe

  # @npm @cli [editly](https://npmjs.com/package/editly) | [GitHub](https://github.com/mifi/editly) | [Homepage](https://github.com/mifi/editly) - A tool and framework for declarative NLE (non-linear video editing) using Node.js and ffmpeg
  - name: editly
    bin: editly

  # @npm @cli [electron](https://npmjs.com/package/electron) | [GitHub](https://github.com/electron/electron) | [Homepage](https://www.electronjs.org/) | [Documentation](https://www.electronjs.org/docs/latest) - A tool that enables to write cross-platform desktop applications using JavaScript, HTML and CSS
  - name: electron
    bin: electron

  # @npm @cli [emma-cli](https://npmjs.com/package/emma-cli) | [GitHub](https://github.com/maticzav/emma-cli) - Install the package you are looking for
  - name: emma-cli
    bin: emma

  # @npm @cli [emoj](https://npmjs.com/package/emoj) | [GitHub](https://github.com/sindresorhus/emoj) - Find relevant emoji from text on the command-line
  - name: emoj
    bin: emoj

  # @npm @cli [empty-trash-cli](https://npmjs.com/package/empty-trash-cli) | [GitHub](https://github.com/sindresorhus/empty-trash-cli) - A CLI to empty the trash
  - name: empty-trash-cli
    bin: empty-trash

  # @npm @cli [eslint](https://npmjs.com/package/eslint) | [GitHub](https://github.com/eslint/eslint) | [Homepage](https://eslint.org/) | [Documentation](https://eslint.org/docs/user-guide/getting-started) - A tool for identifying and reporting on patterns found in ECMAScript/JavaScript code
  - name: eslint
    bin: eslint

  # @npm @cli [fastify-cli](https://npmjs.com/package/fastify-cli) | [GitHub](https://github.com/fastify/fastify-cli) | [Homepage](https://www.fastify.io/) | [Documentation](https://www.fastify.io/docs/latest/) - Command line tools for Fastify. Generate, write, and run an application with one single command
  - name: fastify-cli
    bin: fastify

  # @npm @cli [firebase-tools](https://npmjs.com/package/firebase-tools) | [GitHub](https://github.com/firebase/firebase-tools) | [Homepage](https://firebase.google.com/) | [Documentation](https://firebase.google.com/docs/cli) - The Firebase Command Line Interface (CLI) Tools can be used to test, manage, and deploy Firebase project from the command line
  - name: firebase-tools
    bin: firebase

  # @npm @cli [fkill-cli](https://npmjs.com/package/fkill-cli) | [GitHub](https://github.com/sindresorhus/fkill-cli) - Fabulously kill processes. Cross-platform.
  - name: fkill-cli
    bin: fkill

  # @npm @cli [fx](https://npmjs.com/package/fx) | [GitHub](https://github.com/antonmedv/fx) | [Homepage](https://fx.wtf/) - Command-line JSON processing tool
  - name: fx
    bin: fx

  # @npm @cli [git-open](https://npmjs.com/package/git-open) | [GitHub](https://github.com/paulirish/git-open) - Type git open to open the repo website (GitHub, GitLab, Bitbucket) in browser
  - name: git-open

  # @npm @cli [google-font-installer](https://npmjs.com/package/google-font-installer) | [GitHub](https://github.com/lordgiotto/google-font-installer) - Google Font Installer is a NodeJS module/CLI that lets you Search, Download and Install fonts offered by Google Web Fonts
  - name: google-font-installer
    bin: gfi

  # @npm @cli [gtop](https://npmjs.com/package/gtop) | [GitHub](https://github.com/aksakalli/gtop) - System monitoring dashboard for terminal
  - name: gtop
    bin: gtop

  # @npm @cli [gulp](https://npmjs.com/package/gulp) | [GitHub](https://github.com/gulpjs/gulp) | [Homepage](https://gulpjs.com/) | [Documentation](https://gulpjs.com/docs/en/getting-started/quick-start) - A toolkit that helps you automate painful or time-consuming tasks in your development workflow
  - name: gulp
    bin: gulp

  # @npm @cli [imgur-uploader-cli](https://npmjs.com/package/imgur-uploader-cli) | [GitHub](https://github.com/kevva/imgur-uploader-cli) - CLI to upload images to imgur
  - name: imgur-uploader-cli
    bin: imgur-uploader

  # @npm @cli [ios-deploy](https://npmjs.com/package/ios-deploy) | [GitHub](https://github.com/ios-control/ios-deploy) - Command line tool to install aand debug iOS apps
  - name: ios-deploy
    bin: ios-deploy
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @npm @cli [ipfs-deploy](https://npmjs.com/package/ipfs-deploy) | [GitHub](https://github.com/ipfs-shipyard/ipfs-deploy) - Upload static website to IPFS pinning services and optionally update DNS
  - name: ipfs-deploy
    bin: ipd

  # @npm @cli [is-up-cli](https://npmjs.com/package/is-up-cli) | [GitHub](https://github.com/sindresorhus/is-up-cli) | [Homepage](https://isitup.org/) - Check whether a website is up or down using the isitup.org API
  - name: is-up-cli
    bin: is-up

  # @npm @cli [localtunnel](https://npmjs.com/package/localtunnel) | [GitHub](https://github.com/localtunnel/localtunnel) | [Homepage](localtunnel.me) - localtunnel exposes localhost to the world for easy testing and sharing
  - name: localtunnel
    bin: localtunnel

  # @npm @cli [mjml](https://npmjs.com/package/mjml) | [GitHub](https://github.com/mjmlio/mjml) | [Homepage](https://mjml.io/) | [Documentation](https://documentation.mjml.io/) - A markup language created by Mailjet and designed to reduce the pain of coding a responsive email
  - name: mjml
    bin: mjml

  # @npm @cli [nativefier](https://npmjs.com/package/nativefier) | [GitHub](https://github.com/nativefier/nativefier) | [Documentation](https://github.com/nativefier/nativefier/blob/master/API.md) - Tool to make any web page a desktop application
  - name: nativefier
    bin: nativefier

  # @npm @cli [nectarjs](https://npmjs.com/package/nectarjs) | [GitHub](https://github.com/nectarjs/nectarjs) | [Homepage](https://nectarjs.com/) | [Documentation](https://nectarjs.com/documentation/) - A JavaScript native compiler
  - name: nectarjs
    bin: nectar

  # @npm @cli [newman](https://npmjs.com/package/newman) | [GitHub](https://github.com/postmanlabs/newman) | [Homepage](https://www.postman.com/) | [Documentation](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/) - A command-line collection runner for Postman
  - name: newman
    bin: newman

  # @npm @cli [np](https://npmjs.com/package/np) | [GitHub](https://github.com/sindresorhus/np) - A better npm publish
  - name: np
    bin: np

  # @npm @cli [npm-check](https://npmjs.com/package/npm-check) | [GitHub](https://github.com/dylang/npm-check) | [Homepage](https://www.npmjs.com/package/npm-check) - Check for outdated, incorrect, and unused dependencies
  - name: npm-check
    bin: npm-check

  # @npm @cli [nrm](https://npmjs.com/package/nrm) | [GitHub](https://github.com/Pana/nrm) - nrm can help you easy and fast switch between different npm registries
  - name: nrm
    bin: nrm

  # @npm @cli [oclif](https://npmjs.com/package/oclif) | [GitHub](https://github.com/oclif/oclif) | [Homepage](https://oclif.io/) | [Documentation](https://oclif.io/docs/introduction) - A framework for building CLIs in Node.js
  - name: oclif
    bin: oclif

  # @npm @cli [package-size](https://npmjs.com/package/package-size) | [GitHub](https://github.com/egoist/package-size) - Tool to get the bundle size of an npm package
  - name: package-size
    bin: package-size

  # @npm @cli [pageres-cli](https://npmjs.com/package/pageres-cli) | [GitHub](https://github.com/sindresorhus/pageres-cli) - A CLI to capture screenshots of websites in various resolutions
  - name: pageres-cli
    bin: pageres

  # @npm @cli [playwright](https://npmjs.com/package/playwright) | [GitHub](https://github.com/Microsoft/playwright) | [Homepage](https://playwright.dev/) | [Documentation](https://playwright.dev/docs/intro) - Single API to automate Chromium, WebKit, and Firefox (available as a CLI and library)
  - name: playwright
    bin: playwright

  # @npm @cli [pm2](https://npmjs.com/package/pm2) | [GitHub](https://github.com/Unitech/pm2) | [Homepage](https://pm2.keymetrics.io/) | [Documentation](https://pm2.keymetrics.io/docs/usage/quick-start/) - PM2 is a production process manager for Node.js applications with a built-in load balancer
  - name: pm2
    bin: pm2

  # @npm @cli [pkg](https://npmjs.com/package/pkg) | [GitHub](https://github.com/vercel/pkg) - This command line interface enables you to package your Node.js project into an executable that can be run even on devices without Node.js installed
  - name: pkg
    bin: pkg

  # @npm @cli [prettier](https://npmjs.com/package/prettier) | [GitHub](https://github.com/prettier/prettier) | [Homepage](https://prettier.io/) | [Documentation](https://prettier.io/docs/en/index.html) - A code formatter
  - name: prettier
    bin: prettier

  # @npm @cli [psi](https://npmjs.com/package/psi) | [GitHub](https://github.com/GoogleChromeLabs/psi) | [Homepage](https://pagespeed.web.dev/) | [Documentation](https://developers.google.com/speed/docs/insights/v5/about) - PageSpeed Insights with reporting
  - name: psi
    bin: psi

  # @npm @cli [ramda-cli](https://npmjs.com/package/ramda-cli) | [GitHub](https://github.com/raine/ramda-cli) - A tool for processing data with functional pipelines in the command-line or interactively in browser
  - name: ramda-cli
    bin: ramda

  # @npm @cli [semantic-release](https://npmjs.com/package/semantic-release) | [GitHub](https://github.com/semantic-release/semantic-release) | [Homepage](https://semantic-release.gitbook.io/semantic-release/) | [Documentation](https://semantic-release.gitbook.io/semantic-release/usage/getting-started) - A tool that automates the process of releasing software, featuring integrations with GitHub / GitLab releases
  - name: semantic-release
    bin: semantic-release

  # @npm @cli [serve](https://npmjs.com/package/serve) | [GitHub](https://github.com/vercel/serve) - Static file serving and directory listing
  - name: serve
    bin: serve

  # @npm @cli [serverless](https://npmjs.com/package/serverless) | [GitHub](https://github.com/serverless/serverless) | [Homepage](https://www.serverless.com/) | [Documentation](https://www.serverless.com/framework/docs) - Serverless Framework â€“ Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more
  - name: serverless
    bin: serverless

  # @npm @cli [share-cli](https://npmjs.com/package/share-cli) | [GitHub](https://github.com/marionebl/share-cli) - Quickly share files from your command line
  - name: share-cli
    bin: share

  # @npm @cli [sharp-cli](https://npmjs.com/package/sharp-cli) | [GitHub](https://github.com/vseventer/sharp-cli) - CLI for sharp, a high performance Node.js image processing module
  - name: sharp-cli
    bin: sharp

  # @npm @cli [speed-test](https://npmjs.com/package/speed-test) | [GitHub](https://github.com/sindresorhus/speed-test) - Test your internet connection speed and ping using speedtest.net from the CLI
  - name: speed-test
    bin: speed-test

  # @npm @cli [stegcloak](https://npmjs.com/package/stegcloak) | [GitHub](https://github.com/KuroLabs/stegcloak) | [Homepage](https://stegcloak.surge.sh/) - StegCloak is a pure JavaScript steganography module designed in functional programming style, to hide secrets inside text by compressing and encrypting the secret before cloaking it with special unicode invisible characters
  - name: stegcloak
    bin: stegcloak

  # @npm @cli [supdock](https://npmjs.com/package/supdock) | [GitHub](https://github.com/segersniels/supdock) - A CLI for running commands like "docker logs" in an easier, more interactive way
  - name: supdock
    bin: supdock

  # @npm @cli [surge](https://npmjs.com/package/surge) | [GitHub](https://github.com/sintaxi/surge) | [Homepage](https://surge.sh/) | [Documentation](https://surge.sh/help/) - Publish web apps to a CDN with a single command and no setup required
  - name: surge
    bin: surge

  # @npm @cli [svgo](https://npmjs.com/package/svgo) | [GitHub](https://github.com/svg/svgo) - SVG Optimizer is a Node.js-based tool for optimizing SVG vector graphics files
  - name: svgo
    bin: svgo

  # @npm @cli [terminalizer](https://npmjs.com/package/terminalizer) | [GitHub](https://github.com/faressoft/terminalizer) | [Homepage](https://terminalizer.com/) - Record your terminal and generate animated gif images or share a web player link terminalizer.com
  - name: terminalizer
    bin: terminalizer

  # @npm @cli [tinypng-cli](https://npmjs.com/package/tinypng-cli) | [GitHub](https://github.com/websperts/tinypng-cli) - Handy command line tool for shrinking PNG images using the TinyPNG API
  - name: tinypng-cli
    bin: tinypng

  # @npm @cli [tldr](https://npmjs.com/package/tldr) | [GitHub](https://github.com/tldr-pages/tldr-node-client) | [Homepage](https://tldr.sh/) - A Node.js based command-line client for tldr
  - name: tldr
    bin: tldr

  # @npm @cli [ts2c](https://npmjs.com/package/ts2c) | [GitHub](https://github.com/andrei-markeev/ts2c) - A JavaScript/TypeScript to C compiler
  - name: ts2c
    bin: ts2c

  # @npm @cli [typescript](https://npmjs.com/package/typescript) | [GitHub](https://github.com/Microsoft/TypeScript) | [Homepage](https://www.typescriptlang.org/) | [Documentation](https://www.typescriptlang.org/docs/) - A language for application-scale JavaScript
  - name: typescript
    bin: tsc

  # @npm @cli [wifi-password-cli](https://npmjs.com/package/wifi-password-cli) | [GitHub](https://github.com/kevva/wifi-password-cli) - CLI to get current wifi password
  - name: wifi-password-cli
    bin: wifi-password

  # @npm @cli [wordpressify](https://npmjs.com/package/wordpressify) | [GitHub](https://github.com/luangjokaj/wordpressify) | [Homepage](https://www.wordpressify.co/) | [Documentation](https://www.wordpressify.co/docs) - Automate your WordPress development workflow
  - name: wordpressify
    bin: wordpressify

  # @npm @cli [zx](https://npmjs.com/package/zx) | [GitHub](https://github.com/google/zx) - A tool for writing better scripts
  - name: zx
    bin: zx
