---
# yamllint disable rule:line-length
# @var helm_charts: [] # Settings used for deploying Helm charts. The keys of the `helm_charts` object can be added as an app
# to the `apps` variable (defined in `group_vars/all/apps.yml`) to deploy the application to your network stack.
helm_charts:
  # @helm [Argo](https://argoproj.github.io/cd/) | [GitHub](https://github.com/argoproj/argo-cd) | [Helm](https://github.com/argoproj/argo-helm) - ArgoCD is a declarative GitOps continuous delivery platform.
  argo:
    command: helm install argocd argo/argo-cd
    repository: https://argoproj.github.io/argo-helm
    repository_name: argo
  # @helm [Budibase](https://budibase.com/) | [GitHub](https://github.com/Budibase/budibase) | [Helm](https://docs.budibase.com/docs/kubernetes-k8s) - Budibase is a platform that allows you to codelessly create internal apps in minutes.
  budibase:
    command: helm install --create-namespace --namespace budibase budibase budibase/budibase
    repository: https://budibase.github.io/budibase/
    repository_name: budibase
  # @helm [Cert-Manager](https://cert-manager.io/) | [GitHub](https://github.com/cert-manager/cert-manager) | [Helm](https://cert-manager.io/docs/installation/helm/) - *Cert-Manager* is a powerful and extensible X.509 certificate controller.
  cert-manager:
    command: helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.8.0 --set installCRDs=true
    repository: https://charts.jetstack.io
    repository_name: jetstack
  # @helm [Concourse](https://concourse-ci.org/) | [GitHub](https://github.com/concourse/concourse) | [Helm](https://github.com/concourse/concourse-chart) - Concourse is a sophisticated, open-source CI/CD platform that markets itself as, "the open-source continuous thing-doer."
  concourse:
    command: helm install concourse concourse/concourse
    repository: https://concourse-charts.storage.googleapis.com/
    repository_name: concourse
  # @helm [Consul](https://www.consul.io/) | [GitHub](https://github.com/hashicorp/consul) | [Helm](https://www.consul.io/docs/k8s/installation/install) - HashiCorp Consul is a service networking solution to automate network configurations, discover services, and enable secure connectivity across any cloud or runtime.
  consul:
    command: helm install consul hashicorp/consul --set global.name=consul --create-namespace --namespace consul
    repository: https://helm.releases.hashicorp.com
    repository_name: hashicorp
  # @helm [Drone](https://www.drone.io/) | [GitHub](https://github.com/harness/drone) | [Helm](https://github.com/drone/charts/blob/master/charts/drone/docs/install.md) - Drone is a simple, modern, multi-cloud-capable CI platform written in Go.
  drone:
    command: helm install --namespace drone drone drone/drone -f drone-values.yaml
    repository: https://charts.drone.io
    repository_name: drone
  # @helm [Elastic ECK](https://www.elastic.co/) | [GitHub](https://github.com/elastic/cloud-on-k8s) | [Helm](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-install-helm.html) - Elastic Cloud on Kubernetes (ECK) is the official operator by Elastic for automating the deployment, provisioning, management, and orchestration of Elasticsearch, Kibana, APM Server, Beats, Enterprise Search, Elastic Agent and Elastic Maps Server on Kubernetes.
  elastic:
    command: helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace
    repository: https://helm.elastic.co
    repository_name: elastic
  # @helm [Falco](https://falco.org/) | [GitHub](https://github.com/falcosecurity/falco) | [Helm](https://github.com/falcosecurity/charts) - Falco is *the* cloud-native runtime security project.
  falco:
    command: helm install falco falcosecurity/falco
    repository: https://falcosecurity.github.io/charts
    repository_name: falcosecurity
  # @helm [Fission](https://fission.io/) | [GitHub](https://github.com/fission/fission) | [Helm](https://fission.io/docs/installation/) - Fission is a framework for serverless functions on Kubernetes.
  fission:
    command: helm install --version v1.15.1 --namespace fission fission fission-charts/fission-all
    repository: https://fission.github.io/fission-charts/
    repository_name: fission-charts
  # @helm [GitLab](https://about.gitlab.com/install/ce-or-ee/) | [GitHub](https://github.com/gitlabhq/gitlabhq) | [Helm](https://docs.gitlab.com/operator/installation.html#cluster) - GitLab is a single application that spans the entire software development lifecycle.
  gitlab:
    command: helm install gitlab-operator gitlab-operator/gitlab-operator --create-namespace --namespace gitlab-system
    repository: https://gitlab.com/api/v4/projects/18899486/packages/helm/stable
    repository_name: gitlab-operator
  # @helm [GitLab Runner](https://docs.gitlab.com/runner/) | [GitHub](https://github.com/gitlabhq/gitlab-runner) | [Helm](https://docs.gitlab.com/runner/install/kubernetes.html) - This chart deploys an instance of GitLab runner to a Kubernetes cluster. GitLab runner allows you to attach container/VM instances to GitLab CI workflows.
  gitlab-runner:
    command: helm install --namespace <NAMESPACE> gitlab-runner -f <CONFIG_VALUES_FILE> gitlab/gitlab-runner
    repository: https://charts.gitlab.io
    repository_name: gitlab
  # @helm [Graylog](https://www.graylog.org/) | [GitHub](https://github.com/Graylog2/graylog2-server) | [Helm](https://github.com/KongZ/charts/tree/main/charts/graylog) - Graylog is a leading centralized log management solution for capturing, storing, and enabling real-time analysis of terabytes of machine data.
  graylog:
    command: |
      helm repo add bitnami https://charts.bitnami.com/bitnami
      helm repo add elastic https://helm.elastic.co
      helm install --namespace graylog graylog kongz/graylog
    repository: https://charts.kong-z.com
    repository_name: kongz
  # @helm [Knative](https://knative.dev/docs/) | [GitHub](https://github.com/knative/serving) | [Operator](https://knative.dev/docs/install/operator/knative-with-operators/) -  Knative is an open-source Enterprise-level solution to build serverless and event-driven applications. It manages serverless containers in Kubernetes environments.
  knative:
    operator: https://github.com/knative/operator/releases/download/knative-v1.4.0/operator.yaml
  # @helm [Kubeapps](https://kubeapps.com/) | [GitHub](https://github.com/vmware-tanzu/kubeapps) | [Helm](https://github.com/vmware-tanzu/kubeapps) - Kubeapps is a web-based UI for deploying and managing applications in Kubernetes clusters.
  kubeapps:
    command: helm install kubeapps --namespace kubeapps bitnami/kubeapps
    repository: https://charts.bitnami.com/bitnami
    repository_name: bitnami
  # @helm [Kubernetes Dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) | [GitHub](https://github.com/kubernetes/dashboard) | [Helm](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard) - Kubernetes Dashboard is a general purpose, web-based UI for Kubernetes clusters. It allows users to manage applications running in the cluster and troubleshoot them, as well as manage the cluster itself.
  kubernetes-dashboard:
    command: helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard
    repository: https://kubernetes.github.io/dashboard/
    repository_name: kubernetes-dashboard
  # @helm [Linkerd](https://linkerd.io/) | [GitHub](https://github.com/linkerd/linkerd2) | [Helm](https://linkerd.io/2.10/tasks/install-helm/) - Linkerd is a service mesh that is ultra light, ultra simple, ultra powerful. According to their website, Linkerd adds security, observability, and reliability to Kubernetes, without the complexity.
  linkerd:
    command: |
      if [[ "$OSTYPE" == "darwin"* ]]; then
        CERT_EXP_DATE=$(date -v+8760H +"%Y-%m-%dT%H:%M:%SZ")
      else
        CERT_EXP_DATE=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ")
      fi
      helm install linkerd2 --set-file identityTrustAnchorsPEM=ca.crt --set-file identity.issuer.tls.crtPEM=issuer.crt --set-file identity.issuer.tls.keyPEM=issuer.key --set identity.issuer.crtExpiry=$CERT_EXP_DATE linkerd/linkerd2
    repository: https://helm.linkerd.io/stable
    repository_name: linkered
  # @helm [Loki](https://grafana.com/oss/loki/) | [GitHub](https://github.com/grafana/loki) | [Helm](https://grafana.com/docs/loki/latest/installation/microservices-helm/) - Grafana Loki is a horizontally scalable, highly available, multi-tenant log aggregation system inspired by Prometheus. It is designed to be very cost effective and easy to operate.
  loki:
    command: helm install loki-grafana grafana/grafana
    repository: https://grafana.github.io/helm-charts
    repository_name: grafana
  # @helm [Minio](https://min.io/) | [GitHub](https://github.com/minio/minio) | [Helm](https://github.com/minio/minio/tree/master/helm/minio) - MinIO offers high-performance, S3 compatible object storage. Native to Kubernetes, MinIO is the only object storage suite available on every public cloud, every Kubernetes distribution, the private cloud and the edge.
  minio:
    command: helm install --namespace minio --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio
    repository: https://charts.min.io/
    repository_name: minio
  # @helm [n8n](https://n8n.io/) | [GitHub](https://github.com/n8n-io/n8n) | [Helm](https://artifacthub.io/packages/helm/open-8gears/n8n) - n8n is a free and open-source, self-hostable workflow automation tool that some consider to be a worthy replacement for IFTTT.
  n8n:
    command: helm install n8n open-8gears/n8n
    repository: https://8gears.container-registry.com/chartrepo/library/
    repository_name: open8-gears
  # @helm [Prometheus Operator](https://prometheus-operator.dev/) | [GitHub](https://github.com/prometheus-operator/kube-prometheus) | [Helm](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) - A stack that includes everything required for an HA Prometheus / Grafana setup with pre-configured cluster monitoring and charts. It can also be modified to be used for any purpose that Prometheus / Grafana might be used for.
  prometheus:
    command: helm install prometheus prometheus-community/kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    repository_name: prometheus-community
  # @helm [Rancher](https://rancher.com/) | [GitHub](https://github.com/rancher/rancher) | [Helm](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/) - Rancher is a complete software stack for teams adopting containers. It addresses the operational and security challenges of managing multiple Kubernetes clusters, while providing DevOps teams with integrated tools for running containerized workloads.
  rancher:
    command: |
      # Missing several steps
      helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.my.org --set replicas=3
    repository: https://releases.rancher.com/server-charts/latest
    repository_name: rancher-latest
  # @helm [Sentry](https://sentry.io/welcome/) | [GitHub](https://github.com/getsentry/sentry) | [Helm](https://artifacthub.io/packages/helm/sentry/sentry) - Sentry is the leading open-source error logging application that tracks with full stacktraces & asynchronous context. Sentry's eco-system includes dozens of SDKs, written for many different languages/environments.
  sentry:
    command: helm install sentry sentry/sentry
    repository: https://sentry-kubernetes.github.io/charts
    repository_name: sentry
  # @helm [Space Cloud](https://space-cloud.io/) | [GitHub](https://github.com/spacecloud-io/space-cloud) | [Helm](https://github.com/spacecloud-io/space-cloud/blob/master/install-manifests/helm/index.yaml) - Space Cloud is an open-source Kubernetes-based serverless platform with built-in security and instant GraphQL APIs for any database and microservice.
  space-cloud:
    command: |
      git clone https://github.com/spacecloud-io/space-cloud.git
      cd install-manifests/helm
      helm install space-cloud .
  # @helm [Thanos](https://thanos.io/) | [GitHub](https://github.com/thanos-io/thanos) | [Helm](https://artifacthub.io/packages/helm/bitnami/thanos) - Thanos is an open source, highly available Prometheus setup with long term storage capabilities.
  thanos:
    command: helm install thanos bitnami/thanos
    repository: https://charts.bitnami.com/bitnami
    repository_name: bitnami
  # @helm [Vault](https://www.vaultproject.io/) | [GitHub](https://github.com/hashicorp/vault) | [Helm](https://www.vaultproject.io/docs/platform/k8s/helm) - HashiCorp Vault is a secrets management tool specifically designed to control access to sensitive credentials in a low-trust environment. It can be used to store sensitive values and at the same time dynamically generate access for specific services/applications on lease.
  vault:
    command: helm install vault hashicorp/vault
    repository: https://helm.releases.hashicorp.com
    repository_name: hashicorp
  # @helm [VaultWarden](https://bitwarden.com/) | [GitHub](https://github.com/dani-garcia/vaultwarden) | [Helm](https://artifacthub.io/packages/helm/k8s-at-home/vaultwarden) - VaultWarden is an optimized, resource-efficient version of the open source BitWarden web app (a password management platform).
  vaultwarden:
    command: helm install vaultwarden k8s-at-home/vaultwarden
    repository: https://k8s-at-home.com/charts/
    repository_name: k8s-at-home
  # @helm [Vector](https://vector.dev/) | [GitHub](https://github.com/vectordotdev/vector) | [Helm](https://vector.dev/docs/setup/installation/package-managers/helm/) - Vector is a lightweight, ultra-fast tool for building observability pipelines that lets you collect, transform, and route all your logs and metrics with one simple tool.
  vector:
    command: helm install vector vector/vector --namespace vector --create-namespace --values values.yaml
    repository: https://helm.vector.dev
    repository_name: vector
  # @helm [velero](https://velero.io/) | [GitHub](https://github.com/vmware-tanzu/velero) | [Helm](https://vmware-tanzu.github.io/helm-charts/) - Velero is an open source tool to safely backup and restore, perform disaster recovery, and migrate Kubernetes cluster resources and persistent volumes.
  velero:
    command: helm install vmware-tanzu/velero --namespace <YOUR NAMESPACE> -f values.yaml --generate-name
    repository: https://vmware-tanzu.github.io/helm-charts
    repository_name: vmware-tanzu
