---
samba_allowed_hosts: 127.0.0.1 10.14.141. 10.14.14. 10.0.0.
samba_netbios_name: HTPC
samba_printers:
  - id: HPOfficeJetPro
    comment: HP OfficeJet Pro 6978 (in Garage)
    name: HP OfficeJet Pro 6978
samba_shares:
  - id: Media
    comment: Movies, TV Shows, and other read-only multimedia
    follow_symlinks: true
    path: /mnt/htpc
    public: true
  - id: Private
    comment: Authenticated share with read/write capabilities (backed up to OneDrive)
    follow_symlinks: true
    path: "/home/{{ ansible_user | default(lookup('env', 'USER')) }}/Documents"
    public: false
    users: '@sambausers'
    writable: true
  - id: Public
    comment: Public folder provided for file sharing on the LAN
    path: "/home/{{ ansible_user | default(lookup('env', 'USER')) }}/Public"
    public: true
    writable: true
samba_workgroup: MEGAGROUP
