---
all:
  children:
    desktop:
      hosts:
        malaptop:
          ansible_host: '{{ domains[inventory_hostname | lower].hostname }}'
          ansible_connection: local
          ansible_password: '{{ admin_password }}'
          ansible_python_interpreter: python3
          ansible_sudo_pass: '{{ admin_password }}'
          ansible_user: '{{ admin_username }}'
