---
collections:
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
  - name: ansible.windows
    source: https://galaxy.ansible.com
  - name: chocolatey.chocolatey
    source: https://galaxy.ansible.com
  - name: community.crypto
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: community.windows
    source: https://galaxy.ansible.com
  - name: community.digitalocean
    source: https://galaxy.ansible.com
  - name: freeipa.ansible_freeipa
    source: https://galaxy.ansible.com
